export const handleError = (e) => {
    console.log(e)
}
